name: Terraform Azure IaC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (drives env/<environment>.tfvars)"
        type: choice
        required: true
        options: [dev, uat, prod]
        default: dev
      tf_action:
        description: "Terraform action"
        type: choice
        options: [plan, apply, destroy]
        required: true
        default: plan
      environment_type:
        description: "Env type code (np/p) for naming (locals.tf)"
        type: choice
        options: [np, p]
        required: true
        default: np
      location:
        description: "Azure region display name (e.g., 'UK South')"
        type: string
        required: true
        default: "UK South"
      location_code:
        description: "Short region code used in names (e.g., 'uks')"
        type: string
        required: true
        default: "uks"
      tf_version:
        description: "Terraform version"
        type: string
        required: false
        default: "1.7.5"
      backend_rg:
        default: "tfstate-shared-rg"
        description: "Backend: Resource Group"
        type: string
        required: true
      backend_storage_account:
        default: "sttfstateshared"
        description: "Backend: Storage Account"
        type: string
        required: true
      backend_container:
        default: "tfstate"
        description: "Backend: Blob Container"
        type: string
        required: true
      backend_key_prefix:
        description: "Backend: key prefix (file path prefix for state), e.g., 'iac/core'"
        type: string
        required: false
        default: "iac/core"

jobs:
  terraform:
    name: Terraform ${{ inputs.tf_action }} (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      TF_VAR_environment_type: ${{ inputs.environment_type }}
      TF_VAR_environment_name: ${{ inputs.environment }}
      TF_VAR_location: ${{ inputs.location }}
      TF_VAR_location_code: ${{ inputs.location_code }}

      BACKEND_RG: ${{ inputs.backend_rg }}
      BACKEND_SA: ${{ inputs.backend_storage_account }}
      BACKEND_CONTAINER: ${{ inputs.backend_container }}
      BACKEND_KEY: ${{ inputs.backend_key_prefix }}/${{ inputs.environment }}.tfstate

      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Terraform version
        id: tfver
        run: echo "TF_VERSION=${{ inputs.tf_version }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login (OIDC or secret-based)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}
          # OR (OIDC):
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Display Azure context
        run: |
          az account show
          echo "Using backend key: ${BACKEND_KEY}"

      # ✅ New Step: Automatically create backend RG, Storage Account, Container if missing
      - name: Ensure backend state storage exists (RG/SA/Container)
        env:
          LOCATION: ${{ inputs.location }}
          BACKEND_RG: ${{ inputs.backend_rg }}
          BACKEND_SA: ${{ inputs.backend_storage_account }}
          BACKEND_CONTAINER: ${{ inputs.backend_container }}
        run: |
          set -euo pipefail

          echo "Ensuring resource group '${BACKEND_RG}' (${LOCATION})..."
          az group create -n "${BACKEND_RG}" -l "${LOCATION}" >/dev/null

          echo "Checking storage account '${BACKEND_SA}'..."
          if ! az storage account show -n "${BACKEND_SA}" -g "${BACKEND_RG}" >/dev/null 2>&1; then
            echo "Creating storage account '${BACKEND_SA}'..."
            az storage account create \
              -n "${BACKEND_SA}" \
              -g "${BACKEND_RG}" \
              -l "${LOCATION}" \
              --sku Standard_LRS \
              --kind StorageV2 \
              --allow-blob-public-access false \
              --min-tls-version TLS1_2 >/dev/null
          else
            echo "Storage account exists."
          fi

          echo "Enabling blob protections (versioning, soft delete)..."
          az storage account blob-service-properties update \
            -n "${BACKEND_SA}" -g "${BACKEND_RG}" \
            --enable-versioning true \
            --change-feed-enabled true \
            --delete-retention true --delete-retention-days 7 \
            --container-delete-retention true --container-delete-retention-days 7 >/dev/null

          echo "Ensuring container '${BACKEND_CONTAINER}'..."
          if ! az storage container show \
              --name "${BACKEND_CONTAINER}" \
              --account-name "${BACKEND_SA}" \
              --auth-mode login >/dev/null 2>&1; then
            az storage container create \
              --name "${BACKEND_CONTAINER}" \
              --account-name "${BACKEND_SA}" \
              --auth-mode login >/dev/null
          else
            echo "Container exists."
          fi

          echo "✅ Backend ready"

      - name: Select tfvars file
        id: tfvars
        run: |
          FILE="env/${{ inputs.environment }}.tfvars"
          if [ ! -f "$FILE" ]; then
            echo "ERROR: $FILE not found" >&2
            exit 1
          fi
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Terraform Init (remote backend)
        run: |
          terraform init \
            -backend-config="resource_group_name=${BACKEND_RG}" \
            -backend-config="storage_account_name=${BACKEND_SA}" \
            -backend-config="container_name=${BACKEND_CONTAINER}" \
            -backend-config="key=${BACKEND_KEY}"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ inputs.tf_action == 'plan' || inputs.tf_action == 'apply' }}
        run: |
          terraform plan \
            -var-file="${{ steps.tfvars.outputs.file }}" \
            -out="tfplan-${{ inputs.environment }}.bin"

      - name: Upload Plan Artifact
        if: ${{ inputs.tf_action == 'plan' || inputs.tf_action == 'apply' }}
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ inputs.environment }}
          path: tfplan-${{ inputs.environment }}.bin
          if-no-files-found: error
          retention-days: 7

      - name: Terraform Apply (requires environment approval)
        if: ${{ inputs.tf_action == 'apply' }}
        run: terraform apply -auto-approve "tfplan-${{ inputs.environment }}.bin"

      - name: Terraform Destroy (requires environment approval)
        if: ${{ inputs.tf_action == 'destroy' }}
        run: terraform destroy -auto-approve -var-file="${{ steps.tfvars.outputs.file }}"
